<a href="https://colab.research.google.com/github/Jane-Pereira/Health-Risks-during-Pregnancy/blob/main/pcd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [15]:
dataset = pd.read_csv("https://raw.githubusercontent.com/Jane-Pereira/Health-Risks-during-Pregnancy/main/Maternal%20Health%20Risk%20Data%20Set.csv")

In [26]:
dataset

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]

In [27]:
print(dataset['RiskLevel'].unique())
dataset.info()

['high risk' 'low risk' 'mid risk']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          1014 non-null   int64  
 1   SystolicBP   1014 non-null   int64  
 2   DiastolicBP  1014 non-null   int64  
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64  
 6   RiskLevel    1014 non-null   object 
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB


In [28]:
X = dataset[['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate']].values
y = dataset['RiskLevel'].values

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [30]:
rcla = RandomForestClassifier(n_estimators=500)
rcla.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500)

In [31]:
rpred = rcla.predict(X_test)

In [32]:
rac = accuracy_score(y_test, rpred)
print("Accuracy: ", rac)

Accuracy:  0.8620689655172413


In [33]:
print(confusion_matrix(y_test, rpred))

[[53  1  7]
 [ 1 61 11]
 [ 1  7 61]]


In [34]:
def details():
    data = []
    print('Enter patient report details:')

    data.append(int(input('Age: ')))
    data.append(int(input('SystolicBP: ')))
    data.append(int(input('DiastolicBP: ')))
    data.append(float(input('BS: ')))  # Blood Sugar
    data.append(float(input('BodyTemp: ')))
    data.append(int(input('HeartRate: ')))

    return data

In [35]:
def prediction(data):
    data = np.array(data)
    data = np.reshape(data, (1, -1))  # Reshape to match the number of features (6 now)
    pred = rcla.predict(data)
    return pred


In [36]:
print('- Stage Prediction -')
data = details()

print('Possible Stages: Low, Medium, High')
print('Patient stage: ', prediction(data))

- Stage Prediction -
Enter patient report details:
Age: 35
SystolicBP: 140
DiastolicBP: 90
BS: 13
BodyTemp: 98
HeartRate: 70
Possible Stages: Low, Medium, High
Patient stage:  ['high risk']
